# Capstone Project - Opening a new Mall in Hyderabad, India

Build a dataframe of neighborhoods in Kuala Lumpur, Malaysia by web scraping the data from Wikipedia page
Get the geographical coordinates of the neighborhoods
Obtain the venue data for the neighborhoods from Foursquare API
Explore and cluster the neighborhoods
Select the best cluster to open a new shopping mall

# 1. Import  Libraries

In [1]:
import numpy as np # library to handle data in a vectorized manner

import pandas as pd # library for data analsysis
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)

import json # library to handle JSON files

from geopy.geocoders import Nominatim # convert an address into latitude and longitude values
#import geocoder # to get coordinates

import requests # library to handle requests
from bs4 import BeautifulSoup # library to parse HTML and XML documents

from pandas.io.json import json_normalize # tranform JSON file into a pandas dataframe

# Matplotlib and associated plotting modules
import matplotlib.cm as cm
import matplotlib.colors as colors

# import k-means from clustering stage
from sklearn.cluster import KMeans

import folium # map rendering library

print("Libraries imported.")

Libraries imported.

# 2. Scrap data from Wikipedia page into a DataFrame

In [2]:
# send the GET request
data = requests.get("https://en.wikipedia.org/wiki/List_of_neighbourhoods_in_Hyderabad").text

In [7]:
# parse data from the html into a beautifulsoup object
soup = BeautifulSoup(data, 'html.parser')

In [4]:
# create a list to store neighborhood data
neighborhoodList = []

In [12]:
# append the data into the list
#soup.find_all("span", class_="mw-headline")
for ul in soup.findAll("span", class_="mw-headline"):
    #print(ul.find_all('a'))
    for link in ul.findAll('a'):
        #print (link["title"])
        neighborhoodList.append(link["title"])

In [13]:
# create a new dataframe from the list
hyd_df = pd.DataFrame({"Neighborhood": neighborhoodList})
hyd_df.head()

  Neighborhood
0     Ameerpet
1  Sanathnagar
2  Khairatabad
3  Musheerabad
4     Amberpet

Empty DataFrame
Columns: [Neighborhood]
Index: []

(16, 1)

# 3. Get Geo Co-ordinates

In [8]:
import geocoder

In [9]:
# define a function to get coordinates
def get_latlng(neighborhood):
    # initialize your variable to None
    lat_lng_coords = None
    # loop until you get the coordinates
    while(lat_lng_coords is None):
        g = geocoder.arcgis('{}, Vijayawada, India'.format(neighborhood))
        lat_lng_coords = g.latlng
    return lat_lng_coords

In [10]:
# call the function to get the coordinates, store in a new list using list comprehension
coords = [ get_latlng(neighborhood) for neighborhood in kl_df["Neighborhood"].tolist() ]

In [11]:
coords

[[16.497758471083717, 80.65398692072834],
 [16.516200000000026, 80.70292000000006],
 [16.502560000000074, 80.63977000000006],
 [16.53902217855483, 80.59465104683946],
 [16.521190000000047, 80.77511000000004],
 [16.49663172569585, 80.64539383990157],
 [16.507790000000057, 80.72021000000007],
 [16.56501000000003, 80.67774000000009],
 [15.453910000000064, 74.98688000000004],
 [16.495750000000044, 80.66159000000005],
 [16.47108000000003, 80.72092000000004],
 [16.480680000000064, 80.70790000000005],
 [16.521650000000022, 80.68870000000004],
 [16.525040000000047, 80.68221000000005],
 [16.523696770803298, 80.67692443162882],
 [16.47521000000006, 80.69824000000006]]

In [12]:
# create temporary dataframe to populate the coordinates into Latitude and Longitude
df_coords = pd.DataFrame(coords, columns=['Latitude', 'Longitude'])

In [13]:
# merge the coordinates into the original dataframe
kl_df['Latitude'] = df_coords['Latitude']
kl_df['Longitude'] = df_coords['Longitude']

In [14]:
# check the neighborhoods and the coordinates
print(kl_df.shape)
kl_df

(16, 3)

                    Neighborhood   Latitude  Longitude
0                    Benz Circle  16.497758  80.653987
1                      Enikepadu  16.516200  80.702920
2                        Ganguru  16.502560  80.639770
3          Gollapudi, Vijayawada  16.539022  80.594651
4                    Kesarapalle  16.521190  80.775110
5                 Mogalrajapuram  16.496632  80.645394
6   Nidamanuru, Krishna district  16.507790  80.720210
7                          Nunna  16.565010  80.677740
8           One Town, Vijayawada  15.453910  74.986880
9                       Patamata  16.495750  80.661590
10                    Penamaluru  16.471080  80.720920
11                       Poranki  16.480680  80.707900
12                  Prasadampadu  16.521650  80.688700
13                 Ramavarappadu  16.525040  80.682210
14        Ramavarappadu Junction  16.523697  80.676924
15                    Tadigadapa  16.475210  80.698240

In [15]:
# save the DataFrame as CSV file
kl_df.to_csv("kl_df.csv", index=False)

# 4. Creating a map of Vijayawada with neighborhoods superimposed on top

In [16]:
# get the coordinates of Vijayawada
address = 'Vijayawada, India'

geolocator = Nominatim(user_agent="my-app")
location = geolocator.geocode(address)
latitude = location.latitude
longitude = location.longitude
print('The geograpical coordinate of Vijayawada, India {}, {}.'.format(latitude, longitude))

The geograpical coordinate of Vijayawada, India 16.5087586, 80.6185102.

In [18]:
from IPython.display import HTML, display
# create map of Toronto using latitude and longitude values
map_kl = folium.Map(location=[latitude, longitude], zoom_start=11)

# add markers to map
for lat, lng, neighborhood in zip(kl_df['Latitude'], kl_df['Longitude'], kl_df['Neighborhood']):
    label = '{}'.format(neighborhood)
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lat, lng],
        radius=5,
        popup=label,
        color='blue',
        fill=True,
        fill_color='#3186cc',
        fill_opacity=0.7).add_to(map_kl)  
    
display(map_kl)

In [19]:

# save the map as HTML file
map_kl.save('map_kl.html')

# 5. Use the Foursquare API to explore the neighborhoods

In [20]:
CLIENT_ID = 'YUWOO1JLRIVU0R40QZ05IODMDMDD54DX3DVH5SEXLSZKU5F4' # your Foursquare ID
CLIENT_SECRET = 'KEHYSKHETV4KGPOBLXX3WGGDNR4LGPFKY1Z3WS2PAJPQWZQL' # your Foursquare Secret
VERSION = '20180605' # Foursquare API version

print('Your credentails:')
print('CLIENT_ID: ' + CLIENT_ID)
print('CLIENT_SECRET:' + CLIENT_SECRET)

Your credentails:
CLIENT_ID: YUWOO1JLRIVU0R40QZ05IODMDMDD54DX3DVH5SEXLSZKU5F4
CLIENT_SECRET:KEHYSKHETV4KGPOBLXX3WGGDNR4LGPFKY1Z3WS2PAJPQWZQL

In [21]:
radius = 2000
LIMIT = 100

venues = []

for lat, long, neighborhood in zip(kl_df['Latitude'], kl_df['Longitude'], kl_df['Neighborhood']):
    
    # create the API request URL
    url = "https://api.foursquare.com/v2/venues/explore?client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}".format(
        CLIENT_ID,
        CLIENT_SECRET,
        VERSION,
        lat,
        long,
        radius, 
        LIMIT)
    
    # make the GET request
    results = requests.get(url).json()["response"]['groups'][0]['items']
    
    # return only relevant information for each nearby venue
    for venue in results:
        venues.append((
            neighborhood,
            lat, 
            long, 
            venue['venue']['name'], 
            venue['venue']['location']['lat'], 
            venue['venue']['location']['lng'],  
            venue['venue']['categories'][0]['name']))

In [22]:
# convert the venues list into a new DataFrame
venues_df = pd.DataFrame(venues)

# define the column names
venues_df.columns = ['Neighborhood', 'Latitude', 'Longitude', 'VenueName', 'VenueLatitude', 'VenueLongitude', 'VenueCategory']

print(venues_df.shape)
venues_df.head()

(253, 7)

,Neighborhood,Latitude,Longitude,VenueName,VenueLatitude,VenueLongitude,VenueCategory
0,Benz Circle,16.497758,80.653987,Aptronix,16.497294,80.656273,Electronics Store
1,Benz Circle,16.497758,80.653987,Kitkat,16.501053,80.657670,Bakery
2,Benz Circle,16.497758,80.653987,Baskin-Robbins,16.503227,80.648265,Ice Cream Shop
3,Benz Circle,16.497758,80.653987,"SSS- Idly, Policlinic Road.",16.501898,80.652812,Breakfast Spot
4,Benz Circle,16.497758,80.653987,Talwalkers Better Value Fitness,16.500125,80.656548,Gym

Let's check how many venues were returned for each neighorhood

In [23]:
venues_df.groupby(["Neighborhood"]).count()

,Latitude,Longitude,VenueName,VenueLatitude,VenueLongitude,VenueCategory
Neighborhood,,,,,,
Benz Circle,53,53,53,53,53,53
Enikepadu,5,5,5,5,5,5
Ganguru,54,54,54,54,54,54
"Gollapudi, Vijayawada",5,5,5,5,5,5
Kesarapalle,5,5,5,5,5,5
Mogalrajapuram,46,46,46,46,46,46
"Nidamanuru, Krishna district",5,5,5,5,5,5
Nunna,2,2,2,2,2,2
"One Town, Vijayawada",6,6,6,6,6,6
Patamata,44,44,44,44,44,44
Penamaluru,4,4,4,4,4,4
Poranki,3,3,3,3,3,3
Prasadampadu,5,5,5,5,5,5
Ramavarappadu,6,6,6,6,6,6
Ramavarappadu Junction,7,7,7,7,7,7
Tadigadapa,3,3,3,3,3,3

Let's find out how many unique categories can be curated from all the returned venues

In [24]:
print('There are {} uniques categories.'.format(len(venues_df['VenueCategory'].unique())))

There are 41 uniques categories.

In [25]:
# print out the list of categories
venues_df['VenueCategory'].unique()[:50]

array(['Electronics Store', 'Bakery', 'Ice Cream Shop', 'Breakfast Spot',
       'Gym', 'Fast Food Restaurant', 'Hotel', 'Clothing Store',
       'Multiplex', 'Pizza Place', 'Vegetarian / Vegan Restaurant',
       'Coffee Shop', 'Shopping Mall', 'Café', 'Indian Restaurant',
       'Restaurant', 'Mediterranean Restaurant', 'Pub', 'Movie Theater',
       'Outdoors & Recreation', 'Chocolate Shop', 'Hotel Bar',
       'Smoke Shop', 'Sporting Goods Shop', 'Convenience Store',
       'Train Station', 'Diner', 'Department Store', 'Bookstore',
       'Moving Target', 'Pharmacy', 'Airport Terminal', 'Airport Service',
       'Snack Place', 'Airport Food Court', 'Building', 'Bus Station',
       'Warehouse Store', 'Lawyer', 'Halal Restaurant', 'Garden Center'],
      dtype=object)

In [26]:
# check if the results contain "Shopping Mall"
"Shopping Mall" in venues_df['VenueCategory'].unique()

True

# 6. Analyze Each Neighborhood

In [27]:
# one hot encoding
kl_onehot = pd.get_dummies(venues_df[['VenueCategory']], prefix="", prefix_sep="")

# add neighborhood column back to dataframe
kl_onehot['Neighborhoods'] = venues_df['Neighborhood'] 

# move neighborhood column to the first column
fixed_columns = [kl_onehot.columns[-1]] + list(kl_onehot.columns[:-1])
kl_onehot = kl_onehot[fixed_columns]

print(kl_onehot.shape)
kl_onehot.head()

(253, 42)

,Neighborhoods,Airport Food Court,Airport Service,Airport Terminal,Bakery,Bookstore,Breakfast Spot,Building,Bus Station,Café,Chocolate Shop,Clothing Store,Coffee Shop,Convenience Store,Department Store,Diner,Electronics Store,Fast Food Restaurant,Garden Center,Gym,Halal Restaurant,Hotel,Hotel Bar,Ice Cream Shop,Indian Restaurant,Lawyer,Mediterranean Restaurant,Movie Theater,Moving Target,Multiplex,Outdoors & Recreation,Pharmacy,Pizza Place,Pub,Restaurant,Shopping Mall,Smoke Shop,Snack Place,Sporting Goods Shop,Train Station,Vegetarian / Vegan Restaurant,Warehouse Store
0,Benz Circle,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,Benz Circle,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,Benz Circle,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,Benz Circle,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,Benz Circle,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

Next, let's group rows by neighborhood and by taking the mean of the frequency of occurrence of each category

In [28]:
kl_grouped = kl_onehot.groupby(["Neighborhoods"]).mean().reset_index()

print(kl_grouped.shape)
kl_grouped

(16, 42)

,Neighborhoods,Airport Food Court,Airport Service,Airport Terminal,Bakery,Bookstore,Breakfast Spot,Building,Bus Station,Café,Chocolate Shop,Clothing Store,Coffee Shop,Convenience Store,Department Store,Diner,Electronics Store,Fast Food Restaurant,Garden Center,Gym,Halal Restaurant,Hotel,Hotel Bar,Ice Cream Shop,Indian Restaurant,Lawyer,Mediterranean Restaurant,Movie Theater,Moving Target,Multiplex,Outdoors & Recreation,Pharmacy,Pizza Place,Pub,Restaurant,Shopping Mall,Smoke Shop,Snack Place,Sporting Goods Shop,Train Station,Vegetarian / Vegan Restaurant,Warehouse Store
0,Benz Circle,0.0,0.0,0.0,0.037736,0.000000,0.018868,0.0,0.000000,0.075472,0.018868,0.018868,0.094340,0.0,0.000000,0.000000,0.018868,0.075472,0.000000,0.018868,0.00,0.037736,0.018868,0.056604,0.150943,0.000000,0.018868,0.018868,0.0,0.113208,0.018868,0.000000,0.037736,0.018868,0.018868,0.075472,0.018868,0.0,0.0,0.000000,0.018868,0.0
1,Enikepadu,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.200000,0.000000,0.000000,0.200000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.2,0.200000,0.000000,0.0
2,Ganguru,0.0,0.0,0.0,0.037037,0.018519,0.018519,0.0,0.000000,0.074074,0.000000,0.018519,0.055556,0.0,0.018519,0.037037,0.037037,0.055556,0.000000,0.018519,0.00,0.055556,0.018519,0.055556,0.203704,0.000000,0.018519,0.037037,0.0,0.074074,0.018519,0.000000,0.018519,0.018519,0.018519,0.074074,0.000000,0.0,0.0,0.000000,0.000000,0.0
3,"Gollapudi, Vijayawada",0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.200000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.200000,0.000000,0.000000,0.200000,0.000000,0.000000,0.000000,0.2,0.000000,0.000000,0.200000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0
4,Kesarapalle,0.2,0.4,0.2,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.2,0.0,0.000000,0.000000,0.0
5,Mogalrajapuram,0.0,0.0,0.0,0.043478,0.000000,0.021739,0.0,0.000000,0.086957,0.000000,0.021739,0.065217,0.0,0.000000,0.000000,0.043478,0.086957,0.000000,0.021739,0.00,0.065217,0.021739,0.065217,0.173913,0.000000,0.021739,0.021739,0.0,0.086957,0.021739,0.000000,0.021739,0.021739,0.021739,0.065217,0.000000,0.0,0.0,0.000000,0.000000,0.0
6,"Nidamanuru, Krishna district",0.0,0.0,0.0,0.000000,0.000000,0.000000,0.2,0.000000,0.000000,0.000000,0.000000,0.000000,0.2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.400000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.200000,0.000000,0.0
7,Nunna,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.500000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.5
8,"One Town, Vijayawada",0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.166667,0.166667,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.166667,0.166667,0.000000,0.000000,0.0,0.000000,0.000000,0.333333,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0
9,Patamata,0.0,0.0,0.0,0.045455,0.000000,0.022727,0.0,0.000000,0.090909,0.022727,0.022727,0.090909,0.0,0.022727,0.000000,0.022727,0.090909,0.000000,0.022727,0.00,0.045455,0.000000,0.045455,0.159091,0.000000,0.022727,0.022727,0.0,0.090909,0.022727,0.000000,0.045455,0.022727,0.000000,0.022727,0.022727,0.0,0.0,0.000000,0.022727,0.0
10,Penamaluru,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.250000,0.000000,0.25,0.000000,0.000000,0.000000,0.250000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.250000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0
11,Poranki,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.333333,0.000000,0.00,0.000000,0.000000,0.000000,0.333333,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.333333,0.0,0.0,0.000000,0.000000,0.0
12,Prasadampadu,0.0,0.0,0.0,0.000000,0.000000,0.200000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.200000,0.000000,0.000000,0.400000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.200000,0.000000,0.0
13,Ramavarappadu,0.0,0.0,0.0,0.000000,0.000000,0.166667,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.166667,0.000000,0.000000,0.500000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.166667,0.000000,0.0
14,Ramavarappadu Junction,0.0,0.0,0.0,0.000000,0.000000,0.142857,0.0,0.000000,0.000000,0.142857,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.142857,0.000000,0.000000,0.428571,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.142857,0.000000,0.0
15,Tadigadapa,0.0,0.0,0.0,0.333333,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.333333,0.000000,0.00,0.000000,0.000000,0.000000,0.333333,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0

In [29]:
len(kl_grouped[kl_grouped["Shopping Mall"] > 0])

4

Create a new DataFrame for Shopping Mall data only

In [30]:
kl_mall = kl_grouped[["Neighborhoods","Shopping Mall"]]

In [31]:
kl_mall.head()

           Neighborhoods  Shopping Mall
0            Benz Circle       0.075472
1              Enikepadu       0.000000
2                Ganguru       0.074074
3  Gollapudi, Vijayawada       0.000000
4            Kesarapalle       0.000000

# 7. Cluster Neighborhoods
Run K means to cluster the neighboorhoods in Vijayawada to 3 clusters

In [32]:
# set number of clusters
kclusters = 3

kl_clustering = kl_mall.drop(["Neighborhoods"], 1)

# run k-means clustering
kmeans = KMeans(n_clusters=kclusters, random_state=0).fit(kl_clustering)

# check cluster labels generated for each row in the dataframe
kmeans.labels_[0:]

array([1, 0, 1, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0])

In [33]:
# create a new dataframe that includes the cluster as well as the top 10 venues for each neighborhood.
kl_merged = kl_mall.copy()

# add clustering labels
kl_merged["Cluster Labels"] = kmeans.labels_

In [34]:
kl_merged.rename(columns={"Neighborhoods": "Neighborhood"}, inplace=True)
kl_merged.head()

            Neighborhood  Shopping Mall  Cluster Labels
0            Benz Circle       0.075472               1
1              Enikepadu       0.000000               0
2                Ganguru       0.074074               1
3  Gollapudi, Vijayawada       0.000000               0
4            Kesarapalle       0.000000               0

In [35]:
# merge toronto_grouped with toronto_data to add latitude/longitude for each neighborhood
kl_merged = kl_merged.join(kl_df.set_index("Neighborhood"), on="Neighborhood")

print(kl_merged.shape)
kl_merged.head() # check the last columns!

(16, 5)

            Neighborhood  Shopping Mall  Cluster Labels   Latitude  Longitude
0            Benz Circle       0.075472               1  16.497758  80.653987
1              Enikepadu       0.000000               0  16.516200  80.702920
2                Ganguru       0.074074               1  16.502560  80.639770
3  Gollapudi, Vijayawada       0.000000               0  16.539022  80.594651
4            Kesarapalle       0.000000               0  16.521190  80.775110

In [36]:
# sort the results by Cluster Labels
print(kl_merged.shape)
kl_merged.sort_values(["Cluster Labels"], inplace=True)
kl_merged

(16, 5)

,Neighborhood,Shopping Mall,Cluster Labels,Latitude,Longitude
1,Enikepadu,0.000000,0,16.516200,80.702920
3,"Gollapudi, Vijayawada",0.000000,0,16.539022,80.594651
4,Kesarapalle,0.000000,0,16.521190,80.775110
6,"Nidamanuru, Krishna district",0.000000,0,16.507790,80.720210
7,Nunna,0.000000,0,16.565010,80.677740
8,"One Town, Vijayawada",0.000000,0,15.453910,74.986880
10,Penamaluru,0.000000,0,16.471080,80.720920
11,Poranki,0.000000,0,16.480680,80.707900
12,Prasadampadu,0.000000,0,16.521650,80.688700
13,Ramavarappadu,0.000000,0,16.525040,80.682210
14,Ramavarappadu Junction,0.000000,0,16.523697,80.676924
15,Tadigadapa,0.000000,0,16.475210,80.698240
0,Benz Circle,0.075472,1,16.497758,80.653987
2,Ganguru,0.074074,1,16.502560,80.639770
5,Mogalrajapuram,0.065217,1,16.496632,80.645394
9,Patamata,0.022727,2,16.495750,80.661590

Finally visualize the resulting clusters

In [37]:
# create map
map_clusters = folium.Map(location=[latitude, longitude], zoom_start=11)

# set color scheme for the clusters
x = np.arange(kclusters)
ys = [i+x+(i*x)**2 for i in range(kclusters)]
colors_array = cm.rainbow(np.linspace(0, 1, len(ys)))
rainbow = [colors.rgb2hex(i) for i in colors_array]

# add markers to the map
markers_colors = []
for lat, lon, poi, cluster in zip(kl_merged['Latitude'], kl_merged['Longitude'], kl_merged['Neighborhood'], kl_merged['Cluster Labels']):
    label = folium.Popup(str(poi) + ' - Cluster ' + str(cluster), parse_html=True)
    folium.CircleMarker(
        [lat, lon],
        radius=5,
        popup=label,
        color=rainbow[cluster-1],
        fill=True,
        fill_color=rainbow[cluster-1],
        fill_opacity=0.7).add_to(map_clusters)
       
map_clusters

In [38]:
# save the map as HTML file
map_clusters.save('map_clusters.html')

# 8. Examine clusters
Cluster 0

In [39]:
kl_merged.loc[kl_merged['Cluster Labels'] == 0]

,Neighborhood,Shopping Mall,Cluster Labels,Latitude,Longitude
1,Enikepadu,0.0,0,16.516200,80.702920
3,"Gollapudi, Vijayawada",0.0,0,16.539022,80.594651
4,Kesarapalle,0.0,0,16.521190,80.775110
6,"Nidamanuru, Krishna district",0.0,0,16.507790,80.720210
7,Nunna,0.0,0,16.565010,80.677740
8,"One Town, Vijayawada",0.0,0,15.453910,74.986880
10,Penamaluru,0.0,0,16.471080,80.720920
11,Poranki,0.0,0,16.480680,80.707900
12,Prasadampadu,0.0,0,16.521650,80.688700
13,Ramavarappadu,0.0,0,16.525040,80.682210
14,Ramavarappadu Junction,0.0,0,16.523697,80.676924
15,Tadigadapa,0.0,0,16.475210,80.698240

Cluster 1

In [40]:
kl_merged.loc[kl_merged['Cluster Labels'] == 1]

     Neighborhood  Shopping Mall  Cluster Labels   Latitude  Longitude
0     Benz Circle       0.075472               1  16.497758  80.653987
2         Ganguru       0.074074               1  16.502560  80.639770
5  Mogalrajapuram       0.065217               1  16.496632  80.645394

cluster 2

In [41]:
kl_merged.loc[kl_merged['Cluster Labels'] == 2]

  Neighborhood  Shopping Mall  Cluster Labels  Latitude  Longitude
9     Patamata       0.022727               2  16.49575   80.66159

Observations:

There are only 5 shopping Malls in Vijayawada. In cluster 0, we don't have any shopping malls, In clusetr 2 we have 3 malls and in clusetr 3 we have 2 malls. It is most diserable to select shopping mall in cluster -1